### ISSUE TITLE
Experimental branch - E5108: error executing lua

### ISSUE THREAD

**Issue by lsrdg** [famiu/nvim-reload#5]
Setup with Packer:
`  use { '~/git/nvim-reload', branch = 'experimental' }`

Steps to reproduce error:
- run either `:Reload` or `:Restart`

Full error message:

> CSV Syntax:Invalid column pattern, using default pattern \%([^,]*,\|$\)
> E5108: Error executing lua ...e/pack/packer/start/nvim-reload/lua/nvim-reload/in
> it.lua:154: Vim(lua):E5108: Error executing lua /usr/share/nvim/runtime/lua/vim/
> treesitter/query.lua:291: Overriding nth?

Probably the same error you getting with the branch... I haven't found the reason why this error is showing up, yet, gotta dive deeper in the code next week. With this error I am only able to use the experimental branch while working on the error, and that's why I will roll back to master for everyday use.

**Comment by famiu** [comment]
All discussions regarding the experimental branch should be in #4, so kindly close this and move it there
