### ISSUE TITLE
pre/post reload hooks

### ISSUE THREAD

**Issue by afriemann** [famiu/nvim-reload#6]
I'm currently trying to build some auto reload functionality for the main packer file, however I noticed that feline drops highlights after the reload. Being able to add hooks in config to do this would be super neat.

I could see sth like the following (however I really have no experience with lua whatsoever, I'm just replicating what I've seen over the past days)

```lua
use {
  'famiu/nvim-reload',
  config = function()
    local post_reload = function()
      require('feline').reset_highlights()
      vim.api.nvim_command('syntax on') -- no clue why but syntax seems slightly broken when reloading, probably another plugin
    end

    require('nvim-reload').setup {
      post = post_reload
    }
  end
}
```

**Comment by famiu** [comment]
I added pre/post hooks, check README for more info. Confirm if it all works fine for you so that I might close the issue.

**Comment by afriemann** [comment]
Wow! I'll check it out later today :)

**Comment by afriemann** [comment]
Very cool, works like a charm! :)

```lua
use {
  'famiu/nvim-reload',
  requires = {'nvim-lua/plenary.vim'},
  config = function()
    require('nvim-reload').post_reload_hook = function()
      require('feline').reset_highlights()
    end
  end
}
```
