### ISSUE TITLE
Errors on :Reload and :Restart

### ISSUE THREAD

**Issue by IAmIlliest** [famiu/nvim-reload#7]
Hi,

I'm getting the following when running ':Reload' or ':Restart':
`E5108: Error executing lua ...e\pack\packer\start\nvim-reload\lua\nvim-reload\init.lua:107: bad argument #1 to 'gsub' (string expected, got nil)
`

I haven't added anything specific for nvim-reload to my init.lua or plugins.lua, which is called with require('plugins.lua') from init.lua (which lives under stdpath('config')). I'm just installing it and running it via packer, This is with nvim 0.5.0 on windows. nvim-reload and plenary are pulled as start plugins by packer:

```
  -- Lua Reloading Related
  use {
	  'famiu/nvim-reload',
	  opt = false,
	  requires = {
	  	{'nvim-lua/plenary.nvim', opt = false}
	  }
}
```

Any idea what the issue might be?

**Comment by famiu** [comment]
Do you use Windows, by any chance? If so, that could be why. And if that's the case, sorry to inform you but I don't really plan to go out of my way to support Windows.

**Comment by IAmIlliest** [comment]
I use both Linux and Windows, but in this instance it was on a windows machine; so that probably explains it.

I'm slowly teaching myself a bit about programming so I can contribute a bit more to opensource. If I get to the point of having anything that seems to work, I'll send it your way and you can see if you want to make use of it. That will be a long way off though, as I'm just learning in my spare time, so probably months!

**Comment by famiu** [comment]
Sure, a PR would be more than welcome :)

**Comment by famiu** [comment]
I'm going to close this issue now. Feel free to make a PR once you're done.
